version: 2
updates:
  # Enable pnpm dependency updates
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'pnpm'
    commit-message:
      prefix: 'pnpm'
      prefix-development: 'dev'
      include: 'scope'

  # Enable GitHub Actions updates
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'github-actions'
    commit-message:
      prefix: 'actions'
      include: 'scope'

  # Enable Go module updates
  - package-ecosystem: 'gomod'
    directory: '/src/templates/assets/go/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'go'
    commit-message:
      prefix: 'gomod'
      include: 'scope'
