repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: detect-private-key

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        args: ['--severity=warning', '--external-sources']

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: "\\.(py)$"

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        files: "\\.(py)$"

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.0.0-alpha.1
    hooks:
      - id: eslint
        files: "\\.(js|ts|tsx)$"
        additional_dependencies:
          - eslint@8.51.0
          - typescript@5.2.2
          - '@typescript-eslint/eslint-plugin@6.9.0'
          - '@typescript-eslint/parser@6.9.0'

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: "\\.(js|ts|tsx|json|yml|yaml|md)$"
