name: Flask-React CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    uses: ./.github/workflows/python-workflow.yml
    with:
      working_directory: ./backend
      requirements_file: requirements.txt
      test_command: pytest
      lint_command: flake8

  frontend:
    uses: ./.github/workflows/node-workflow.yml
    with:
      working_directory: ./frontend
      package_manager: pnpm
      build_command: build
      test_command: test
      lint_command: lint

  integration:
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and test integration
        run: |
          echo "Add integration tests here"
