name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go-ci:
    uses: ./.github/workflows/go-workflow.yml
    with:
      working_directory: .
      test_flags: '-v -race -coverprofile=coverage.out'
      lint_command: 'golangci-lint run --timeout=5m'
