name: Pre-commit Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files_yaml: |
            all:
              - '**/*'

      - name: Run pre-commit on all files
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: pre-commit run --all-files

      - name: Run pre-commit on changed files
        if: github.event_name == 'pull_request'
        run: |
          echo "Running pre-commit on changed files:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"
          pre-commit run --files ${{ steps.changed-files.outputs.all_changed_files }}
