name: Dependabot PNPM Support

on:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.3.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Update pnpm lockfile
        run: pnpm install --no-frozen-lockfile

      - name: Commit updated lockfile
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update pnpm lockfile'
          file_pattern: 'pnpm-lock.yaml'
          commit_user_name: 'dependabot[bot]'
          commit_user_email: '49699333+dependabot[bot]@users.noreply.github.com'
