name: Test Templates

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '9.3.0'
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: |
            package.json
            src/tests/package.json

      - name: Generate pnpm lock files
        run: |
          # Generate root pnpm-lock.yaml
          pnpm install --no-frozen-lockfile
          
          # Generate test pnpm-lock.yaml
          cd src/tests
          pnpm install --no-frozen-lockfile

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install BATS
        run: |
          pnpm install -g bats-core
          bats --version

      - name: Verify shell scripts
        run: |
          chmod +x ./craftingbench.sh
          chmod +x ./src/tests/run-tests.sh
          bash -n ./craftingbench.sh
          bash -n ./src/tests/run-tests.sh

      - name: Run tests
        run: ./src/tests/run-tests.sh

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: |
            src/tests/test-output
            src/tests/coverage
          retention-days: 5
